---
title: "Adiposity Radiomics"
author: "Christelle Colin-Leitzinger"
date: '`r Sys.Date()`'
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
    theme: united
    highlight: pygments
    df_print: paged
editor_options: 
  chunk_output_type: console
---

<style type="text/css">

.figure {
   margin-top: 25px;
   margin-bottom: 100px;
}

table {
    margin-top: 10px;
    margin-bottom: 25px;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      cache = FALSE,
                      fig.align='center'
                      )
options(gtsummary.print_engine = "gt")
options(gtsummary.as_gt.addl_cmds = "gt::tab_options(table.font.size = 14, data_row.padding = gt::px(1))")
```

```{r library}
library(tidyverse)
library(mclust)
library(data.table)
library(gtsummary)
library(survival)
library(survminer)
```

```{r load test-retest}
path <- fs::path("","Volumes","Peres_Research", "Ovarian - Radiomics", "CTbased adiposity")

adipose_data <- read_rds(paste0(here::here(), "/adipose_data.rds")) %>% 
  filter(!is.na(tnm_cs_mixed_group_stage))
```

<br>

Note: I excluded the patient noted in "should exclude" variable.  
Also the patient with missing TNM was removed.  

<br>

***

```{r tertile}
adipose_data <- adipose_data %>% 
  mutate(tertile = ntile(muscle_area_cm2, 3)) %>% 
  mutate(tert_muscle_area_cm2 = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_muscle_area_cm2 = factor(tert_muscle_area_cm2, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(muscle_area_cm2_ind, 3)) %>% 
  mutate(tert_muscle_area_cm2_ind = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_muscle_area_cm2_ind = factor(tert_muscle_area_cm2_ind, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(imat_area_cm2, 3)) %>% 
  mutate(tert_imat_area_cm2 = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_imat_area_cm2 = factor(tert_imat_area_cm2, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(imat_area_cm2_ind, 3)) %>% 
  mutate(tert_imat_area_cm2_ind = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_imat_area_cm2_ind = factor(tert_imat_area_cm2_ind, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(vat_area_cm2, 3)) %>% 
  mutate(tert_vat_area_cm2 = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_vat_area_cm2 = factor(tert_vat_area_cm2, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(vat_area_cm2_ind, 3)) %>% 
  mutate(tert_vat_area_cm2_ind = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_vat_area_cm2_ind = factor(tert_vat_area_cm2_ind, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(sat_area_cm2, 3)) %>% 
  mutate(tert_sat_area_cm2 = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_sat_area_cm2 = factor(tert_sat_area_cm2, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(sat_area_cm2_ind, 3)) %>% 
  mutate(tert_sat_area_cm2_ind = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_sat_area_cm2_ind = factor(tert_sat_area_cm2_ind, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(total_fat_area, 3)) %>% 
  mutate(tert_total_fat_area = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_total_fat_area = factor(tert_total_fat_area, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(total_fat_area_ind, 3)) %>% 
  mutate(tert_total_fat_area_ind = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_total_fat_area_ind = factor(tert_total_fat_area_ind, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(muscle_mean_hu, 3)) %>% 
  mutate(tert_muscle_mean_hu = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_muscle_mean_hu = factor(tert_muscle_mean_hu, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(imat_mean_hu, 3)) %>% 
  mutate(tert_imat_mean_hu = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_imat_mean_hu = factor(tert_imat_mean_hu, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(muscle_hu_sd, 3)) %>% 
  mutate(tert_muscle_hu_sd = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_muscle_hu_sd = factor(tert_muscle_hu_sd, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(v_s_ratio, 3)) %>% 
  mutate(tert_v_s_ratio = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_v_s_ratio = factor(tert_v_s_ratio, levels = c("Low", "Medium", "High"))) %>% 
  select(-tertile)
```

# Data summary

## Pre-treatment CT-based measures of adiposity

```{r}
tbl1 <- adipose_data %>% 
  select(sat_area_cm2, 
         imat_area_cm2,
         vat_area_cm2
         ) %>% 
  tbl_summary(
            statistic=list(all_continuous() ~ "{mean}"), 
            digits = all_continuous() ~ 1
            ) %>%  
  bold_labels() %>% 
  modify_footnote(update = everything() ~ NA)

tbl2 <- adipose_data %>% 
  select(sat_area_cm2, 
         imat_area_cm2,
         vat_area_cm2
         ) %>% 
  tbl_summary(
            statistic=list(all_continuous() ~ "{min} - {max}"), 
            digits = all_continuous() ~ 1
            ) %>%  
  bold_labels() %>% 
  modify_footnote(update = everything() ~ NA)

tbl3 <- adipose_data %>% 
  select(sat_area_cm2, 
         imat_area_cm2,
         vat_area_cm2
         ) %>% 
  tbl_summary(
            statistic=list(all_continuous() ~ "{median}"), 
            digits = all_continuous() ~ 1
            ) %>%  
  bold_labels() %>% 
  modify_footnote(update = everything() ~ NA)
tbl_merge(list(tbl1, tbl2, tbl3), tab_spanner = c("Mean", "Min-Max", "Median"))


tbl3 <- adipose_data %>% 
  select(tert_sat_area_cm2, sat_area_cm2) %>% 
  tbl_summary(by = tert_sat_area_cm2,
            statistic=list(all_continuous() ~ "{min} - {max}"), 
            digits = all_continuous() ~ 1
            ) %>%  
  bold_labels()

tbl4 <- adipose_data %>% 
  select(tert_imat_area_cm2, imat_area_cm2) %>% 
  tbl_summary(by = tert_imat_area_cm2,
            statistic=list(all_continuous() ~ "{min} - {max}"), 
            digits = all_continuous() ~ 1
            ) %>%  
  bold_labels()

tbl5 <- adipose_data %>% 
  select(tert_vat_area_cm2, vat_area_cm2) %>% 
  tbl_summary(by = tert_vat_area_cm2,
            statistic=list(all_continuous() ~ "{min} - {max}"), 
            digits = all_continuous() ~ 1
            ) %>%  
  bold_labels()
tbl_stack(list(tbl3, tbl4, tbl5))
```
<br>


<!-- ## HR for tertiles -->
<!-- ### Recurrence -->
<!-- Multivariable anlyses are adjusted by `+ raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type`.   -->
<!-- For visceral features the first table is not adjusted by ascites while the second table is.   -->
```{r HR tertiles recurrence}
# tbl1 <- adipose_data %>% select(rec_event, recurrence_time,
#                                 tert_muscle_area_cm2, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$recurrence_time,
#                              event = adipose_data$rec_event)),
#                    exponentiate = TRUE, 
#                    include = tert_muscle_area_cm2) %>% 
#   bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$recurrence_time,
#          event = adipose_data$rec_event) ~ tert_muscle_area_cm2 + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_muscle_area_cm2) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(rec_event, recurrence_time,
#                                 tert_muscle_area_cm2_ind, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$recurrence_time,
#                              event = adipose_data$rec_event)),
#                    exponentiate = TRUE, 
#                  include = tert_muscle_area_cm2_ind) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$recurrence_time,
#          event = adipose_data$rec_event) ~ tert_muscle_area_cm2_ind + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_muscle_area_cm2_ind) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(rec_event, recurrence_time,
#                                 tert_imat_area_cm2, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$recurrence_time,
#                              event = adipose_data$rec_event)),
#                    exponentiate = TRUE, 
#                  include = tert_imat_area_cm2) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$recurrence_time,
#          event = adipose_data$rec_event) ~ tert_imat_area_cm2 + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_imat_area_cm2) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(rec_event, recurrence_time,
#                                 tert_imat_area_cm2_ind, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$recurrence_time,
#                              event = adipose_data$rec_event)),
#                    exponentiate = TRUE, 
#                  include = tert_imat_area_cm2_ind) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$recurrence_time,
#          event = adipose_data$rec_event) ~ tert_imat_area_cm2_ind + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_imat_area_cm2_ind) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(rec_event, recurrence_time,
#                                 tert_vat_area_cm2, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$recurrence_time,
#                              event = adipose_data$rec_event)),
#                    exponentiate = TRUE, 
#                  include = tert_vat_area_cm2) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$recurrence_time,
#          event = adipose_data$rec_event) ~ tert_vat_area_cm2 + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_vat_area_cm2) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(rec_event, recurrence_time,
#                                 tert_vat_area_cm2, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type, ascites) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$recurrence_time,
#                              event = adipose_data$rec_event)),
#                    exponentiate = TRUE, 
#                  include = tert_vat_area_cm2) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$recurrence_time,
#          event = adipose_data$rec_event) ~ tert_vat_area_cm2 + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type + ascites,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_vat_area_cm2) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(rec_event, recurrence_time,
#                                 tert_vat_area_cm2_ind, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$recurrence_time,
#                              event = adipose_data$rec_event)),
#                    exponentiate = TRUE, 
#                  include = tert_vat_area_cm2_ind) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$recurrence_time,
#          event = adipose_data$rec_event) ~ tert_vat_area_cm2_ind + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_vat_area_cm2_ind) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# 
# tbl1 <- adipose_data %>% select(rec_event, recurrence_time,
#                                 tert_vat_area_cm2_ind, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type, ascites) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$recurrence_time,
#                              event = adipose_data$rec_event)),
#                    exponentiate = TRUE, 
#                  include = tert_vat_area_cm2_ind) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$recurrence_time,
#          event = adipose_data$rec_event) ~ tert_vat_area_cm2_ind + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type + ascites,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_vat_area_cm2_ind) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(rec_event, recurrence_time,
#                                 tert_sat_area_cm2, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$recurrence_time,
#                              event = adipose_data$rec_event)),
#                    exponentiate = TRUE, 
#                  include = tert_sat_area_cm2) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$recurrence_time,
#          event = adipose_data$rec_event) ~ tert_sat_area_cm2 + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_sat_area_cm2) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(rec_event, recurrence_time,
#                                 tert_sat_area_cm2_ind, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$recurrence_time,
#                              event = adipose_data$rec_event)),
#                    exponentiate = TRUE, 
#                  include = tert_sat_area_cm2_ind) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$recurrence_time,
#          event = adipose_data$rec_event) ~ tert_sat_area_cm2_ind + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_sat_area_cm2_ind) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(rec_event, recurrence_time,
#                                 tert_total_fat_area, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$recurrence_time,
#                              event = adipose_data$rec_event)),
#                    exponentiate = TRUE, 
#                  include = tert_total_fat_area) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$recurrence_time,
#          event = adipose_data$rec_event) ~ tert_total_fat_area + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_total_fat_area) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(rec_event, recurrence_time,
#                                 tert_total_fat_area_ind, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$recurrence_time,
#                              event = adipose_data$rec_event)),
#                    exponentiate = TRUE, 
#                  include = tert_total_fat_area_ind) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$recurrence_time,
#          event = adipose_data$rec_event) ~ tert_total_fat_area_ind + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_total_fat_area_ind) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(rec_event, recurrence_time,
#                                 tert_muscle_mean_hu, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$recurrence_time,
#                              event = adipose_data$rec_event)),
#                    exponentiate = TRUE, 
#                  include = tert_muscle_mean_hu) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$recurrence_time,
#          event = adipose_data$rec_event) ~ tert_muscle_mean_hu + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_muscle_mean_hu) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(rec_event, recurrence_time,
#                                 tert_imat_mean_hu, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$recurrence_time,
#                              event = adipose_data$rec_event)),
#                    exponentiate = TRUE, 
#                  include = tert_imat_mean_hu) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$recurrence_time,
#          event = adipose_data$rec_event) ~ tert_imat_mean_hu + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_imat_mean_hu) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(rec_event, recurrence_time,
#                                 tert_muscle_hu_sd, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$recurrence_time,
#                              event = adipose_data$rec_event)),
#                    exponentiate = TRUE, 
#                  include = tert_muscle_hu_sd) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$recurrence_time,
#          event = adipose_data$rec_event) ~ tert_muscle_hu_sd + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_muscle_hu_sd) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(rec_event, recurrence_time,
#                                 tert_v_s_ratio, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$recurrence_time,
#                              event = adipose_data$rec_event)),
#                    exponentiate = TRUE, 
#                  include = tert_v_s_ratio) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$recurrence_time,
#          event = adipose_data$rec_event) ~ tert_v_s_ratio + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_v_s_ratio) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(rec_event, recurrence_time,
#                                 tert_v_s_ratio, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type, ascites) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$recurrence_time,
#                              event = adipose_data$rec_event)),
#                    exponentiate = TRUE, 
#                  include = tert_v_s_ratio) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$recurrence_time,
#          event = adipose_data$rec_event) ~ tert_v_s_ratio + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type + ascites,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_v_s_ratio) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
```

<!-- ### OS -->
```{r HR tertiles os}
# tbl1 <- adipose_data %>% select(os_event, os_time,
#                                 tert_muscle_area_cm2, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$os_time,
#                              event = adipose_data$os_event)),
#                    exponentiate = TRUE, 
#                  include = tert_muscle_area_cm2) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$os_time,
#          event = adipose_data$os_event) ~ tert_muscle_area_cm2 + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_muscle_area_cm2) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(os_event, os_time,
#                                 tert_muscle_area_cm2_ind, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$os_time,
#                              event = adipose_data$os_event)),
#                    exponentiate = TRUE, 
#                  include = tert_muscle_area_cm2_ind) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$os_time,
#          event = adipose_data$os_event) ~ tert_muscle_area_cm2_ind + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_muscle_area_cm2_ind) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(os_event, os_time,
#                                 tert_imat_area_cm2, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$os_time,
#                              event = adipose_data$os_event)),
#                    exponentiate = TRUE, 
#                  include = tert_imat_area_cm2) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$os_time,
#          event = adipose_data$os_event) ~ tert_imat_area_cm2 + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_imat_area_cm2) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(os_event, os_time,
#                                 tert_imat_area_cm2_ind, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$os_time,
#                              event = adipose_data$os_event)),
#                    exponentiate = TRUE, 
#                  include = tert_imat_area_cm2_ind) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$os_time,
#          event = adipose_data$os_event) ~ tert_imat_area_cm2_ind + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_imat_area_cm2_ind) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(os_event, os_time,
#                                 tert_vat_area_cm2, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$os_time,
#                              event = adipose_data$os_event)),
#                    exponentiate = TRUE, 
#                  include = tert_vat_area_cm2) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$os_time,
#          event = adipose_data$os_event) ~ tert_vat_area_cm2 + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_vat_area_cm2) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(os_event, os_time,
#                                 tert_vat_area_cm2, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type, ascites) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$os_time,
#                              event = adipose_data$os_event)),
#                    exponentiate = TRUE, 
#                  include = tert_vat_area_cm2) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$os_time,
#          event = adipose_data$os_event) ~ tert_vat_area_cm2 + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type + ascites,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_vat_area_cm2) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(os_event, os_time,
#                                 tert_vat_area_cm2_ind, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$os_time,
#                              event = adipose_data$os_event)),
#                    exponentiate = TRUE, 
#                  include = tert_vat_area_cm2_ind) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$os_time,
#          event = adipose_data$os_event) ~ tert_vat_area_cm2_ind + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_vat_area_cm2_ind) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(os_event, os_time,
#                                 tert_vat_area_cm2_ind, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type, ascites) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$os_time,
#                              event = adipose_data$os_event)),
#                    exponentiate = TRUE, 
#                  include = tert_vat_area_cm2_ind) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$os_time,
#          event = adipose_data$os_event) ~ tert_vat_area_cm2_ind + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type + ascites,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_vat_area_cm2_ind) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(os_event, os_time,
#                                 tert_sat_area_cm2, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$os_time,
#                              event = adipose_data$os_event)),
#                    exponentiate = TRUE, 
#                  include = tert_sat_area_cm2) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$os_time,
#          event = adipose_data$os_event) ~ tert_sat_area_cm2 + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_sat_area_cm2) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(os_event, os_time,
#                                 tert_sat_area_cm2_ind, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$os_time,
#                              event = adipose_data$os_event)),
#                    exponentiate = TRUE, 
#                  include = tert_sat_area_cm2_ind) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$os_time,
#          event = adipose_data$os_event) ~ tert_sat_area_cm2_ind + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_sat_area_cm2_ind) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(os_event, os_time,
#                                 tert_total_fat_area, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$os_time,
#                              event = adipose_data$os_event)),
#                    exponentiate = TRUE, 
#                  include = tert_total_fat_area) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$os_time,
#          event = adipose_data$os_event) ~ tert_total_fat_area + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_total_fat_area) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(os_event, os_time,
#                                 tert_total_fat_area_ind, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$os_time,
#                              event = adipose_data$os_event)),
#                    exponentiate = TRUE, 
#                  include = tert_total_fat_area_ind) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$os_time,
#          event = adipose_data$os_event) ~ tert_total_fat_area_ind + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_total_fat_area_ind) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(os_event, os_time,
#                                 tert_muscle_mean_hu, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$os_time,
#                              event = adipose_data$os_event)),
#                    exponentiate = TRUE, 
#                  include = tert_muscle_mean_hu) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$os_time,
#          event = adipose_data$os_event) ~ tert_muscle_mean_hu + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_muscle_mean_hu) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(os_event, os_time,
#                                 tert_imat_mean_hu, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$os_time,
#                              event = adipose_data$os_event)),
#                    exponentiate = TRUE, 
#                  include = tert_imat_mean_hu) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$os_time,
#          event = adipose_data$os_event) ~ tert_imat_mean_hu + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_imat_mean_hu) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(os_event, os_time,
#                                 tert_muscle_hu_sd, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$os_time,
#                              event = adipose_data$os_event)),
#                    exponentiate = TRUE, 
#                  include = tert_muscle_hu_sd) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$os_time,
#          event = adipose_data$os_event) ~ tert_muscle_hu_sd + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_muscle_hu_sd) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(os_event, os_time,
#                                 tert_v_s_ratio, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$os_time,
#                              event = adipose_data$os_event)),
#                    exponentiate = TRUE, 
#                  include = tert_v_s_ratio) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$os_time,
#          event = adipose_data$os_event) ~ tert_v_s_ratio + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_v_s_ratio) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- adipose_data %>% select(os_event, os_time,
#                                 tert_v_s_ratio, 
#                                 raceeth1, age_at_diagnosis, tnm_cs_mixed_group_stage, 
#                                 treatment_type, ascites) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = adipose_data$os_time,
#                              event = adipose_data$os_event)),
#                    exponentiate = TRUE, 
#                  include = tert_v_s_ratio) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
#   bold_labels() %>% italicize_levels()
# tbl2 <-
#   coxph(Surv(time = adipose_data$os_time,
#          event = adipose_data$os_event) ~ tert_v_s_ratio + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type + ascites,
#     data =  adipose_data) %>%
#   tbl_regression(exponentiate = TRUE, 
#                  include = tert_v_s_ratio) %>% bold_p(t = .05)
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
```

















