---
title: "Adiposity Radiomics"
author: "Christelle Colin-Leitzinger"
date: '`r Sys.Date()`'
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
    theme: united
    highlight: pygments
    df_print: paged
editor_options: 
  chunk_output_type: console
---

<style type="text/css">
.figure {
   margin-top: 25px;
   <!-- margin-bottom: 100px; -->
}

table {
    margin-top: 10px;
    margin-bottom: 25px;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      cache = FALSE,
                      # fig.width = 7, fig.height = 5, 
                      fig.align='center'#, fig.show='hold'
                      )
options(gtsummary.print_engine = "gt")
options(gtsummary.as_gt.addl_cmds = "gt::tab_options(table.font.size = 14, data_row.padding = gt::px(1))")
```

```{r library}
library(tidyverse)
library(data.table)
library(gtsummary)
library(survival)
library(survminer)
```

```{r load test-retest}
path <- fs::path("","Volumes","Peres_Research", "Ovarian - Radiomics", "CTbased adiposity")

adipose_data <- read_rds(paste0(here::here(), "/adipose_data.rds"))
```

<br>

# Data summary
## Table 1. Distribution of patient characteristics overall

```{r}
adipose_data %>% 
  select(age_at_diagnosis, year_of_diagnosis, raceeth, treatment_type, 
         debulking_status, tnm_cs_mixed_group_stage, ecog_pretrt, 
         preDx_comorbidities, preDx_hypertension, preDx_diabetes_mellitus, 
         preDx_hypercholesterolemia, preDx_cardiac_conditions, 
         preDx_chronic_kidney_disease, 
         vital_new, os_time, 
         has_the_patient_recurred, recurrence_time) %>% 
  
  tbl_summary(
    type = list(year_of_diagnosis ~ "categorical", 
                          all_dichotomous() ~ "categorical"), 
            statistic=list(all_continuous() ~ "{mean} ({sd})"), 
            digits = all_continuous() ~ 1
    ) %>%  
  bold_labels() %>% add_stat_label() %>% 
  modify_footnote(update = everything() ~ NA)
```

## Table 2. CT-based measures of adiposity

```{r}
adipose_data %>% 
  select("thickness", "muscle_area_cm2", muscle_area_cm2_ind,
         imat_area_cm2, imat_area_cm2_ind,
         vat_area_cm2, vat_area_cm2_ind,
         sat_area_cm2, sat_area_cm2_ind,
         muscle_mean_hu,                    
         imat_mean_hu, vat_mean_hu, sat_mean_hu,                       
         muscle_hu_sd, imat_hu_sd, vat_hu_sd,                         
         sat_hu_sd, v_s_ratio, 
         "total_fat_area", total_fat_area_ind) %>% 
  tbl_summary(
            statistic=list(all_continuous() ~ "{mean} ({sd})"), 
            digits = all_continuous() ~ 1
            ) %>%  
  bold_labels() %>% add_stat_label() %>% 
  modify_footnote(update = everything() ~ NA)
```

```{r}
adipose_data %>% 
  select(mrn, bmi_cat,
         "muscle_area_cm2", muscle_area_cm2_ind,
         imat_area_cm2, imat_area_cm2_ind,
         vat_area_cm2, vat_area_cm2_ind,
         sat_area_cm2, sat_area_cm2_ind,
         "total_fat_area", total_fat_area_ind,
         muscle_mean_hu,                    
         imat_mean_hu,
         muscle_hu_sd, v_s_ratio) %>% 
  pivot_longer(-c(mrn, bmi_cat)) %>% 
  ggplot(aes(x= name, y= value, color = bmi_cat))+
  geom_boxplot()+
  theme_minimal()+
  coord_flip()

adipose_data %>% 
  select(mrn, bmi_cat,
         "muscle_area_cm2", muscle_area_cm2_ind,
         imat_area_cm2, imat_area_cm2_ind,
         vat_area_cm2, vat_area_cm2_ind,
         sat_area_cm2, sat_area_cm2_ind,
         "total_fat_area", total_fat_area_ind,
         muscle_mean_hu,                    
         imat_mean_hu,
         muscle_hu_sd, v_s_ratio) %>% 
  pivot_longer(-c(mrn, bmi_cat)) %>% 
  ggplot(aes(x= bmi_cat, y= value, color = bmi_cat))+
  geom_boxplot()+
  theme_minimal()+
  coord_flip()+
  # facet_grid(cols = vars(name), scales = "free")
  facet_wrap(.~ name, scales = "free")
```

## KM

```{r}
mysurv <- Surv(adipose_data$recurrence_time, event = adipose_data$rec_event)
myplot <- survfit(mysurv~bmi_cat, data = adipose_data)
ggsurvplot(myplot, data = adipose_data,
           title = "Recurrence Analysis",
           font.main = c(24, "bold", "black"),
           font.x = c(20, "bold", "black"),
           font.y = c(20, "bold", "black"),
           font.legend = c(20, "bold", "black"),
           font.tickslab = c(18, "bold", "black"),
           size = 1.5,

           xlab = "Time in months",
           legend = "top",
           legend.title = "",
           # legend.labs = c("White Non-Hispanic", "Hispanic", "Black"),
           # palette = c("#03051AFF", "blue", "red"),
           pval = TRUE,
           conf.int = FALSE,
           # Censor
           censor = TRUE
) + guides(colour = guide_legend(nrow = 3))
```

```{r}
tbl1 <- adipose_data %>% select(rec_event, recurrence_time,
                            raceeth, age_at_diagnosis, tnm_cs_mixed_group_stage, treatment_type,
                            bmi, bmi_cat) %>%
  tbl_uvregression(method = survival::coxph,
                   y = (Surv(time = adipose_data$recurrence_time,
                             event = adipose_data$rec_event)),
                   exponentiate = TRUE) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
  bold_labels() %>% italicize_levels()
tbl2 <- 
  coxph(Surv(time = adipose_data$recurrence_time,
             event = adipose_data$rec_event) ~ raceeth + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type + bmi_cat, data =  adipose_data) %>%
  tbl_regression(exponentiate = TRUE) %>% bold_p(t = .05)
tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
```

```{r}
mysurv <- Surv(adipose_data$os_time, event = adipose_data$os_event)
myplot <- survfit(mysurv~bmi_cat, data = adipose_data)
ggsurvplot(myplot, data = adipose_data,
           title = "OS Analysis",
           font.main = c(24, "bold", "black"),
           font.x = c(20, "bold", "black"),
           font.y = c(20, "bold", "black"),
           font.legend = c(20, "bold", "black"),
           font.tickslab = c(18, "bold", "black"),
           size = 1.5,

           xlab = "Time in months",
           legend = "top",
           legend.title = "",
           # legend.labs = c("White Non-Hispanic", "Hispanic", "Black"),
           # palette = c("#03051AFF", "blue", "red"),
           pval = TRUE,
           conf.int = FALSE,
           # Censor
           censor = TRUE
) + guides(colour = guide_legend(nrow = 3))
```

```{r}
tbl1 <- adipose_data %>% select(os_event, os_time,
                            raceeth, age_at_diagnosis, tnm_cs_mixed_group_stage, treatment_type,
                            bmi, bmi_cat) %>%
  tbl_uvregression(method = survival::coxph,
                   y = (Surv(time = adipose_data$os_time,
                             event = adipose_data$os_event)),
                   exponentiate = TRUE) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
  bold_labels() %>% italicize_levels()
tbl2 <- 
  coxph(Surv(time = adipose_data$os_time,
             event = adipose_data$os_event) ~ raceeth + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type + bmi_cat, data =  adipose_data) %>%
  tbl_regression(exponentiate = TRUE) %>% bold_p(t = .05)
tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
```
<br>
<br>

```{r}
adipose_data %>% select(rec_event, recurrence_time,
                            "muscle_area_cm2", muscle_area_cm2_ind,
         imat_area_cm2, imat_area_cm2_ind,
         vat_area_cm2, vat_area_cm2_ind,
         sat_area_cm2, sat_area_cm2_ind,
         "total_fat_area", total_fat_area_ind,
         muscle_mean_hu,                    
         imat_mean_hu,
         muscle_hu_sd, v_s_ratio) %>%
  tbl_uvregression(method = survival::coxph,
                   y = (Surv(time = adipose_data$recurrence_time,
                             event = adipose_data$rec_event)),
                   exponentiate = TRUE) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
  bold_labels() %>% italicize_levels()

adipose_data %>% select(os_event, os_time,
                            "muscle_area_cm2", muscle_area_cm2_ind,
         imat_area_cm2, imat_area_cm2_ind,
         vat_area_cm2, vat_area_cm2_ind,
         sat_area_cm2, sat_area_cm2_ind,
         "total_fat_area", total_fat_area_ind,
         muscle_mean_hu,                    
         imat_mean_hu,
         muscle_hu_sd, v_s_ratio) %>%
  tbl_uvregression(method = survival::coxph,
                   y = (Surv(time = adipose_data$os_time,
                             event = adipose_data$os_event)),
                   exponentiate = TRUE) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level") %>%
  bold_labels() %>% italicize_levels()
```




