---
title: "KM IMAT Adiposity Radiomics"
author: "Christelle Colin-Leitzinger"
date: '`r Sys.Date()`'
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
    theme: united
    highlight: pygments
    df_print: paged
editor_options: 
  chunk_output_type: console
---

<style type="text/css">

.figure {
   margin-top: 25px;
   margin-bottom: 100px;
}

table {
    margin-top: 10px;
    margin-bottom: 25px;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      cache = FALSE,
                      fig.align='center'
                      )
options(gtsummary.print_engine = "gt")
options(gtsummary.as_gt.addl_cmds = "gt::tab_options(table.font.size = 14, data_row.padding = gt::px(1))")
```

```{r library}
library(tidyverse)
library(ggplot2)
library(data.table)
library(survival)
library(survminer)
```

```{r load data}
adipose_data <- read_rds(paste0(here::here(), "/adipose_data.rds"))

adipose_data <- adipose_data %>% 
  mutate(tertile = ntile(muscle_area_cm2, 3)) %>% 
  mutate(tert_muscle_area_cm2 = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_muscle_area_cm2 = factor(tert_muscle_area_cm2, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(muscle_area_cm2_ind, 3)) %>% 
  mutate(tert_muscle_area_cm2_ind = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_muscle_area_cm2_ind = factor(tert_muscle_area_cm2_ind, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(imat_area_cm2, 3)) %>% 
  mutate(tert_imat_area_cm2 = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_imat_area_cm2 = factor(tert_imat_area_cm2, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(imat_area_cm2_ind, 3)) %>% 
  mutate(tert_imat_area_cm2_ind = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_imat_area_cm2_ind = factor(tert_imat_area_cm2_ind, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(vat_area_cm2, 3)) %>% 
  mutate(tert_vat_area_cm2 = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_vat_area_cm2 = factor(tert_vat_area_cm2, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(vat_area_cm2_ind, 3)) %>% 
  mutate(tert_vat_area_cm2_ind = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_vat_area_cm2_ind = factor(tert_vat_area_cm2_ind, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(sat_area_cm2, 3)) %>% 
  mutate(tert_sat_area_cm2 = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_sat_area_cm2 = factor(tert_sat_area_cm2, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(sat_area_cm2_ind, 3)) %>% 
  mutate(tert_sat_area_cm2_ind = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_sat_area_cm2_ind = factor(tert_sat_area_cm2_ind, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(total_fat_area, 3)) %>% 
  mutate(tert_total_fat_area = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_total_fat_area = factor(tert_total_fat_area, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(total_fat_area_ind, 3)) %>% 
  mutate(tert_total_fat_area_ind = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_total_fat_area_ind = factor(tert_total_fat_area_ind, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(muscle_mean_hu, 3)) %>% 
  mutate(tert_muscle_mean_hu = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_muscle_mean_hu = factor(tert_muscle_mean_hu, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(imat_mean_hu, 3)) %>% 
  mutate(tert_imat_mean_hu = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_imat_mean_hu = factor(tert_imat_mean_hu, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(muscle_hu_sd, 3)) %>% 
  mutate(tert_muscle_hu_sd = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_muscle_hu_sd = factor(tert_muscle_hu_sd, levels = c("Low", "Medium", "High"))) %>% 
  mutate(tertile = ntile(v_s_ratio, 3)) %>% 
  mutate(tert_v_s_ratio = case_when(
    tertile == 1 ~ "Low",
    tertile == 2 ~ "Medium",
    tertile == 3 ~ "High",
  ), 
  tert_v_s_ratio = factor(tert_v_s_ratio, levels = c("Low", "Medium", "High"))) %>% 
  select(-tertile)
```

<br>

# Recurrence

The adjusted curves (second) are adjusted by ` raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type`.
NOT adjusted by `treatment_type` in stratified treatment.

## Overall
```{r}
surv_model <-
  survfit(Surv(time = recurrence_time, event = rec_event) ~ tert_imat_area_cm2, data = adipose_data)
ggsurvplot(surv_model, data = adipose_data,
           title = "Recurrence Free Survival analysis - Overall",
           font.main = c(16, "bold", "black"),
           font.x = c(20, "bold", "black"),
           font.y = c(20, "bold", "black"),
           font.legend = c(20, "black"),
           font.tickslab = c(18, "bold", "black"),
           size = 1.5,
           
           xlab = "Time (months)",
           legend.title = "",
           legend.labs = c("Low", "Medium", "High"),
           palette = c("deepskyblue", "darkolivegreen3", "blue4"),
           pval = TRUE,
           pval.coord = c(0, 0.1),
           conf.int = FALSE,
           risk.table = FALSE
) + guides(colour = guide_legend(ncol = 1))

adipose_data_frame <- adipose_data %>% as.data.frame()
fit <- 
  coxph(Surv(time = recurrence_time, event = rec_event) ~ 
          tert_imat_area_cm2 + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage + treatment_type, 
        data = adipose_data_frame)
ggadjustedcurves(fit, data = adipose_data_frame, 
                 method = "average", 
                 variable = "tert_imat_area_cm2",
                 palette = c("deepskyblue", "darkolivegreen3", "blue4")
                 )
```

## Upfront Chemo
```{r}
adipose_data_neo <- adipose_data %>% 
  filter(treatment_type == "Upfront Neoadjuvant")
```
  
```{r}
surv_model <-
  survfit(Surv(time = recurrence_time, event = rec_event) ~ tert_imat_area_cm2, data = adipose_data_neo)
ggsurvplot(surv_model, data = adipose_data_neo,
           title = "Recurrence Free Survival analysis - Upfront Chemo",
           font.main = c(16, "bold", "black"),
           font.x = c(20, "bold", "black"),
           font.y = c(20, "bold", "black"),
           font.legend = c(20, "black"),
           font.tickslab = c(18, "bold", "black"),
           size = 1.5,
           
           xlab = "Time (months)",
           legend.title = "",
           legend.labs = c("Low", "Medium", "High"),
           palette = c("deepskyblue", "darkolivegreen3", "blue4"), # navy, teal and then kind of a darker lime green
           pval = TRUE,
           pval.coord = c(0, 0.1),
           conf.int = FALSE,
           risk.table = FALSE
) + guides(colour = guide_legend(ncol = 1))

adipose_data_neo_frame <- adipose_data_neo %>% as.data.frame()
fit <- 
  coxph(Surv(time = recurrence_time, event = rec_event) ~ 
          tert_imat_area_cm2 + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage, 
        data = adipose_data_neo_frame)
ggadjustedcurves(fit, data = adipose_data_neo_frame, 
                 method = "average", 
                 variable = "tert_imat_area_cm2",
                 palette = c("deepskyblue", "darkolivegreen3", "blue4")
                 )
```

## Upfront surgery

```{r}
adipose_data_surg <- adipose_data %>% 
  filter(treatment_type == "Upfront Surgery")
```

```{r}
surv_model <-
  survfit(Surv(time = recurrence_time, event = rec_event) ~ tert_imat_area_cm2, data = adipose_data_surg)
ggsurvplot(surv_model, data = adipose_data_surg,
           title = "Recurrence Free Survival analysis - Upfront surgery",
           font.main = c(16, "bold", "black"),
           font.x = c(20, "bold", "black"),
           font.y = c(20, "bold", "black"),
           font.legend = c(20, "black"),
           font.tickslab = c(18, "bold", "black"),
           size = 1.5,
           
           xlab = "Time (months)",
           legend.title = "",
           legend.labs = c("Low", "Medium", "High"),
           palette = c("deepskyblue", "darkolivegreen3", "blue4"), # navy, teal and then kind of a darker lime green
           pval = TRUE,
           pval.coord = c(0, 0.1),
           conf.int = FALSE,
           risk.table = FALSE
) + guides(colour = guide_legend(ncol = 1))

a <- adipose_data_surg %>% filter(tert_imat_area_cm2 == "Low"| tert_imat_area_cm2 == "High")
surv_model <-
  survfit(Surv(time = recurrence_time, event = rec_event) ~ tert_imat_area_cm2, data = a)
ggsurvplot(surv_model, data = a,
           title = "Recurrence Free Survival analysis - Upfront surgery",
           font.main = c(16, "bold", "black"),
           font.x = c(20, "bold", "black"),
           font.y = c(20, "bold", "black"),
           font.legend = c(20, "black"),
           font.tickslab = c(18, "bold", "black"),
           size = 1.5,
           
           xlab = "Time (months)",
           legend.title = "",
           # legend.labs = c("Low", "Medium", "High"),
           # palette = c("deepskyblue", "darkolivegreen3", "blue4"), # navy, teal and then kind of a darker lime green
           pval = TRUE,
           pval.coord = c(0, 0.1),
           conf.int = FALSE,
           risk.table = FALSE
) + guides(colour = guide_legend(ncol = 1))

a <- adipose_data_surg %>% filter(tert_imat_area_cm2 == "Low"| tert_imat_area_cm2 == "Medium")
surv_model <-
  survfit(Surv(time = recurrence_time, event = rec_event) ~ tert_imat_area_cm2, data = a)
ggsurvplot(surv_model, data = a,
           title = "Recurrence Free Survival analysis - Upfront surgery",
           font.main = c(16, "bold", "black"),
           font.x = c(20, "bold", "black"),
           font.y = c(20, "bold", "black"),
           font.legend = c(20, "black"),
           font.tickslab = c(18, "bold", "black"),
           size = 1.5,
           
           xlab = "Time (months)",
           legend.title = "",
           # legend.labs = c("Low", "Medium", "High"),
           # palette = c("deepskyblue", "darkolivegreen3", "blue4"), # navy, teal and then kind of a darker lime green
           pval = TRUE,
           pval.coord = c(0, 0.1),
           conf.int = FALSE,
           risk.table = FALSE
) + guides(colour = guide_legend(ncol = 1))

adipose_data_surg_frame <- adipose_data_surg %>% as.data.frame()
fit <- 
  coxph(Surv(time = recurrence_time, event = rec_event) ~ 
          tert_imat_area_cm2 + raceeth1 + age_at_diagnosis + tnm_cs_mixed_group_stage, 
        data = adipose_data_surg_frame)
ggadjustedcurves(fit, data = adipose_data_surg_frame, 
                 method = "average", 
                 variable = "tert_imat_area_cm2",
                 palette = c("deepskyblue", "darkolivegreen3", "blue4")
                 )
```

